- name: Install required packages
  apt:
    name:
      - systemd-sysv # systemctl is missing from the template
      - curl
      - jq
      - zip
      - tree
    state: present

- name: Install required packages on dev
  apt:
    name:
      - default-jdk
    state: present
  when: inventory_hostname == "atlas"

- name: Ensure system locale is set to C.UTF-8
  lineinfile:
    path: /etc/default/locale
    regexp: '^LANG='
    line: 'LANG="C.UTF-8"'
    create: yes
